services:
  backend:
    image: f1app-backend:latest
    container_name: f1app-backend
    restart: unless-stopped
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: f1user
      DB_PASSWORD: f1fantasy_password_2025
      DB_NAME: f1fantasy
      PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - f1app-network

  frontend:
    image: f1app-frontend:latest
    container_name: f1app-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - f1app-network

networks:
  f1app-network:
    driver: bridge
