package main

// GPURLs contiene las URLs de todos los GPs de la temporada 2025
var GPURLs = map[string]map[string]string{
	"australian": {
		"name":         "Australian Grand Prix",
		"race":         "https://www.formula1.com/en/results/2025/races/1260/australia/race-result",
		"qualifying":   "https://www.formula1.com/en/results/2025/races/1260/australia/qualifying",
		"practice1":    "https://www.formula1.com/en/results/2025/races/1260/australia/practice/1",
		"practice2":    "https://www.formula1.com/en/results/2025/races/1260/australia/practice/2",
		"practice3":    "https://www.formula1.com/en/results/2025/races/1260/australia/practice/3",
		"pit_stops":    "https://www.formula1.com/en/results/2025/races/1260/australia/pit-stop-summary",
		"fastest_laps": "https://www.formula1.com/en/results/2025/races/1260/australia/fastest-laps",
		"gp_index":     "1",
	},
	"austrian": {
		"name":         "Austrian Grand Prix",
		"race":         "https://www.formula1.com/en/results/2025/races/1264/austria/race-result",
		"qualifying":   "https://www.formula1.com/en/results/2025/races/1264/austria/qualifying",
		"practice1":    "https://www.formula1.com/en/results/2025/races/1264/austria/practice/1",
		"practice2":    "https://www.formula1.com/en/results/2025/races/1264/austria/practice/2",
		"practice3":    "https://www.formula1.com/en/results/2025/races/1264/austria/practice/3",
		"pit_stops":    "https://www.formula1.com/en/results/2025/races/1264/austria/pit-stop-summary",
		"fastest_laps": "https://www.formula1.com/en/results/2025/races/1264/austria/fastest-laps",
		"gp_index":     "11",
	},
	"azerbaijan": {
		"name":         "Azerbaijan Grand Prix",
		"race":         "https://www.formula1.com/en/results/2025/races/1269/azerbaijan/race-result",
		"qualifying":   "https://www.formula1.com/en/results/2025/races/1269/azerbaijan/qualifying",
		"practice1":    "https://www.formula1.com/en/results/2025/races/1269/azerbaijan/practice/1",
		"practice2":    "https://www.formula1.com/en/results/2025/races/1269/azerbaijan/practice/2",
		"practice3":    "https://www.formula1.com/en/results/2025/races/1269/azerbaijan/practice/3",
		"pit_stops":    "https://www.formula1.com/en/results/2025/races/1269/azerbaijan/pit-stop-summary",
		"fastest_laps": "https://www.formula1.com/en/results/2025/races/1269/azerbaijan/fastest-laps",
		"gp_index":     "17",
	},
	"bahrain": {
		"name":         "Bahrain Grand Prix",
		"race":         "https://www.formula1.com/en/results/2025/races/1261/bahrain/race-result",
		"qualifying":   "https://www.formula1.com/en/results/2025/races/1261/bahrain/qualifying",
		"practice1":    "https://www.formula1.com/en/results/2025/races/1261/bahrain/practice/1",
		"practice2":    "https://www.formula1.com/en/results/2025/races/1261/bahrain/practice/2",
		"practice3":    "https://www.formula1.com/en/results/2025/races/1261/bahrain/practice/3",
		"pit_stops":    "https://www.formula1.com/en/results/2025/races/1261/bahrain/pit-stop-summary",
		"fastest_laps": "https://www.formula1.com/en/results/2025/races/1261/bahrain/fastest-laps",
		"gp_index":     "4",
	},
	"belgian": {
		"name":         "Belgian Grand Prix",
		"race":         "https://www.formula1.com/en/results/2025/races/1265/belgium/race-result",
		"qualifying":   "https://www.formula1.com/en/results/2025/races/1265/belgium/qualifying",
		"practice1":    "https://www.formula1.com/en/results/2025/races/1265/belgium/practice/1",
		"practice2":    "https://www.formula1.com/en/results/2025/races/1265/belgium/practice/2",
		"practice3":    "https://www.formula1.com/en/results/2025/races/1265/belgium/practice/3",
		"pit_stops":    "https://www.formula1.com/en/results/2025/races/1265/belgium/pit-stop-summary",
		"fastest_laps": "https://www.formula1.com/en/results/2025/races/1265/belgium/fastest-laps",
		"gp_index":     "13",
	},
	"brazilian": {
		"name":         "Brazilian Grand Prix",
		"race":         "https://www.formula1.com/en/results/2025/races/1275/brazil/race-result",
		"qualifying":   "https://www.formula1.com/en/results/2025/races/1275/brazil/qualifying",
		"practice1":    "https://www.formula1.com/en/results/2025/races/1275/brazil/practice/1",
		"practice2":    "https://www.formula1.com/en/results/2025/races/1275/brazil/practice/2",
		"practice3":    "https://www.formula1.com/en/results/2025/races/1275/brazil/practice/3",
		"pit_stops":    "https://www.formula1.com/en/results/2025/races/1275/brazil/pit-stop-summary",
		"fastest_laps": "https://www.formula1.com/en/results/2025/races/1275/brazil/fastest-laps",
		"gp_index":     "21",
	},
	"british": {
		"name":         "British Grand Prix",
		"race":         "https://www.formula1.com/en/results/2025/races/1263/great-britain/race-result",
		"qualifying":   "https://www.formula1.com/en/results/2025/races/1263/great-britain/qualifying",
		"practice1":    "https://www.formula1.com/en/results/2025/races/1263/great-britain/practice/1",
		"practice2":    "https://www.formula1.com/en/results/2025/races/1263/great-britain/practice/2",
		"practice3":    "https://www.formula1.com/en/results/2025/races/1263/great-britain/practice/3",
		"pit_stops":    "https://www.formula1.com/en/results/2025/races/1263/great-britain/pit-stop-summary",
		"fastest_laps": "https://www.formula1.com/en/results/2025/races/1263/great-britain/fastest-laps",
		"gp_index":     "12",
	},
	"canadian": {
		"name":         "Canadian Grand Prix",
		"race":         "https://www.formula1.com/en/results/2025/races/1262/canada/race-result",
		"qualifying":   "https://www.formula1.com/en/results/2025/races/1262/canada/qualifying",
		"practice1":    "https://www.formula1.com/en/results/2025/races/1262/canada/practice/1",
		"practice2":    "https://www.formula1.com/en/results/2025/races/1262/canada/practice/2",
		"practice3":    "https://www.formula1.com/en/results/2025/races/1262/canada/practice/3",
		"pit_stops":    "https://www.formula1.com/en/results/2025/races/1262/canada/pit-stop-summary",
		"fastest_laps": "https://www.formula1.com/en/results/2025/races/1262/canada/fastest-laps",
		"gp_index":     "10",
	},
	"chinese": {
		"name":         "Chinese Grand Prix",
		"race":         "https://www.formula1.com/en/results/2025/races/1255/china/race-result",
		"qualifying":   "https://www.formula1.com/en/results/2025/races/1255/china/qualifying",
		"practice1":    "https://www.formula1.com/en/results/2025/races/1255/china/practice-1",
		"practice2":    "https://www.formula1.com/en/results/2025/races/1255/china/practice-2",
		"practice3":    "https://www.formula1.com/en/results/2025/races/1255/china/practice-3",
		"pit_stops":    "https://www.formula1.com/en/results/2025/races/1255/china/pit-stop-summary",
		"fastest_laps": "https://www.formula1.com/en/results/2025/races/1255/china/fastest-laps",
		"gp_index":     "2",
	},
	"dutch": {
		"name":         "Dutch Grand Prix",
		"race":         "https://www.formula1.com/en/results/2025/races/1267/netherlands/race-result",
		"qualifying":   "https://www.formula1.com/en/results/2025/races/1267/netherlands/qualifying",
		"practice1":    "https://www.formula1.com/en/results/2025/races/1267/netherlands/practice/1",
		"practice2":    "https://www.formula1.com/en/results/2025/races/1267/netherlands/practice/2",
		"practice3":    "https://www.formula1.com/en/results/2025/races/1267/netherlands/practice/3",
		"pit_stops":    "https://www.formula1.com/en/results/2025/races/1267/netherlands/pit-stop-summary",
		"fastest_laps": "https://www.formula1.com/en/results/2025/races/1267/netherlands/fastest-laps",
		"gp_index":     "15",
	},
	"emilia_romagna": {
		"name":         "Emilia Romagna Grand Prix",
		"race":         "https://www.formula1.com/en/results/2025/races/1261/emilia-romagna/race-result",
		"qualifying":   "https://www.formula1.com/en/results/2025/races/1261/emilia-romagna/qualifying",
		"practice1":    "https://www.formula1.com/en/results/2025/races/1261/emilia-romagna/practice/1",
		"practice2":    "https://www.formula1.com/en/results/2025/races/1261/emilia-romagna/practice/2",
		"practice3":    "https://www.formula1.com/en/results/2025/races/1261/emilia-romagna/practice/3",
		"pit_stops":    "https://www.formula1.com/en/results/2025/races/1261/emilia-romagna/pit-stop-summary",
		"fastest_laps": "https://www.formula1.com/en/results/2025/races/1261/emilia-romagna/fastest-laps",
		"gp_index":     "7",
	},
	"hungarian": {
		"name":         "Hungarian Grand Prix",
		"race":         "https://www.formula1.com/en/results/2025/races/1266/hungary/race-result",
		"qualifying":   "https://www.formula1.com/en/results/2025/races/1266/hungary/qualifying",
		"practice1":    "https://www.formula1.com/en/results/2025/races/1266/hungary/practice/1",
		"practice2":    "https://www.formula1.com/en/results/2025/races/1266/hungary/practice/2",
		"practice3":    "https://www.formula1.com/en/results/2025/races/1266/hungary/practice/3",
		"pit_stops":    "https://www.formula1.com/en/results/2025/races/1266/hungary/pit-stop-summary",
		"fastest_laps": "https://www.formula1.com/en/results/2025/races/1266/hungary/fastest-laps",
		"gp_index":     "14",
	},
	"italian": {
		"name":         "Italian Grand Prix",
		"race":         "https://www.formula1.com/en/results/2025/races/1268/italy/race-result",
		"qualifying":   "https://www.formula1.com/en/results/2025/races/1268/italy/qualifying",
		"practice1":    "https://www.formula1.com/en/results/2025/races/1268/italy/practice/1",
		"practice2":    "https://www.formula1.com/en/results/2025/races/1268/italy/practice/2",
		"practice3":    "https://www.formula1.com/en/results/2025/races/1268/italy/practice/3",
		"pit_stops":    "https://www.formula1.com/en/results/2025/races/1268/italy/pit-stop-summary",
		"fastest_laps": "https://www.formula1.com/en/results/2025/races/1268/italy/fastest-laps",
		"gp_index":     "16",
	},
	"japanese": {
		"name":         "Japanese Grand Prix",
		"race":         "https://www.formula1.com/en/results/2025/races/1271/japan/race-result",
		"qualifying":   "https://www.formula1.com/en/results/2025/races/1271/japan/qualifying",
		"practice1":    "https://www.formula1.com/en/results/2025/races/1271/japan/practice/1",
		"practice2":    "https://www.formula1.com/en/results/2025/races/1271/japan/practice/2",
		"practice3":    "https://www.formula1.com/en/results/2025/races/1271/japan/practice/3",
		"pit_stops":    "https://www.formula1.com/en/results/2025/races/1271/japan/pit-stop-summary",
		"fastest_laps": "https://www.formula1.com/en/results/2025/races/1271/japan/fastest-laps",
		"gp_index":     "3",
	},
	"las_vegas": {
		"name":         "Las Vegas Grand Prix",
		"race":         "https://www.formula1.com/en/results/2025/races/1276/las-vegas/race-result",
		"qualifying":   "https://www.formula1.com/en/results/2025/races/1276/las-vegas/qualifying",
		"practice1":    "https://www.formula1.com/en/results/2025/races/1276/las-vegas/practice/1",
		"practice2":    "https://www.formula1.com/en/results/2025/races/1276/las-vegas/practice/2",
		"practice3":    "https://www.formula1.com/en/results/2025/races/1276/las-vegas/practice/3",
		"pit_stops":    "https://www.formula1.com/en/results/2025/races/1276/las-vegas/pit-stop-summary",
		"fastest_laps": "https://www.formula1.com/en/results/2025/races/1276/las-vegas/fastest-laps",
		"gp_index":     "22",
	},
	"mexican": {
		"name":         "Mexican Grand Prix",
		"race":         "https://www.formula1.com/en/results/2025/races/1274/mexico/race-result",
		"qualifying":   "https://www.formula1.com/en/results/2025/races/1274/mexico/qualifying",
		"practice1":    "https://www.formula1.com/en/results/2025/races/1274/mexico/practice/1",
		"practice2":    "https://www.formula1.com/en/results/2025/races/1274/mexico/practice/2",
		"practice3":    "https://www.formula1.com/en/results/2025/races/1274/mexico/practice/3",
		"pit_stops":    "https://www.formula1.com/en/results/2025/races/1274/mexico/pit-stop-summary",
		"fastest_laps": "https://www.formula1.com/en/results/2025/races/1274/mexico/fastest-laps",
		"gp_index":     "20",
	},
	"miami": {
		"name":         "Miami Grand Prix",
		"race":         "https://www.formula1.com/en/results/2025/races/1261/miami/race-result",
		"qualifying":   "https://www.formula1.com/en/results/2025/races/1261/miami/qualifying",
		"practice1":    "https://www.formula1.com/en/results/2025/races/1261/miami/practice/1",
		"practice2":    "https://www.formula1.com/en/results/2025/races/1261/miami/practice/2",
		"practice3":    "https://www.formula1.com/en/results/2025/races/1261/miami/practice/3",
		"pit_stops":    "https://www.formula1.com/en/results/2025/races/1261/miami/pit-stop-summary",
		"fastest_laps": "https://www.formula1.com/en/results/2025/races/1261/miami/fastest-laps",
		"gp_index":     "6",
	},
	"monaco": {
		"name":         "Monaco Grand Prix",
		"race":         "https://www.formula1.com/en/results/2025/races/1262/monaco/race-result",
		"qualifying":   "https://www.formula1.com/en/results/2025/races/1262/monaco/qualifying",
		"practice1":    "https://www.formula1.com/en/results/2025/races/1262/monaco/practice/1",
		"practice2":    "https://www.formula1.com/en/results/2025/races/1262/monaco/practice/2",
		"practice3":    "https://www.formula1.com/en/results/2025/races/1262/monaco/practice/3",
		"pit_stops":    "https://www.formula1.com/en/results/2025/races/1262/monaco/pit-stop-summary",
		"fastest_laps": "https://www.formula1.com/en/results/2025/races/1262/monaco/fastest-laps",
		"gp_index":     "8",
	},
	"qatar": {
		"name":         "Qatar Grand Prix",
		"race":         "https://www.formula1.com/en/results/2025/races/1272/qatar/race-result",
		"qualifying":   "https://www.formula1.com/en/results/2025/races/1272/qatar/qualifying",
		"practice1":    "https://www.formula1.com/en/results/2025/races/1272/qatar/practice/1",
		"practice2":    "https://www.formula1.com/en/results/2025/races/1272/qatar/practice/2",
		"practice3":    "https://www.formula1.com/en/results/2025/races/1272/qatar/practice/3",
		"pit_stops":    "https://www.formula1.com/en/results/2025/races/1272/qatar/pit-stop-summary",
		"fastest_laps": "https://www.formula1.com/en/results/2025/races/1272/qatar/fastest-laps",
		"gp_index":     "23",
	},
	"saudi_arabian": {
		"name":         "Saudi Arabian Grand Prix",
		"race":         "https://www.formula1.com/en/results/2025/races/1261/saudi-arabia/race-result",
		"qualifying":   "https://www.formula1.com/en/results/2025/races/1261/saudi-arabia/qualifying",
		"practice1":    "https://www.formula1.com/en/results/2025/races/1261/saudi-arabia/practice/1",
		"practice2":    "https://www.formula1.com/en/results/2025/races/1261/saudi-arabia/practice/2",
		"practice3":    "https://www.formula1.com/en/results/2025/races/1261/saudi-arabia/practice/3",
		"pit_stops":    "https://www.formula1.com/en/results/2025/races/1261/saudi-arabia/pit-stop-summary",
		"fastest_laps": "https://www.formula1.com/en/results/2025/races/1261/saudi-arabia/fastest-laps",
		"gp_index":     "5",
	},
	"singapore": {
		"name":         "Singapore Grand Prix",
		"race":         "https://www.formula1.com/en/results/2025/races/1270/singapore/race-result",
		"qualifying":   "https://www.formula1.com/en/results/2025/races/1270/singapore/qualifying",
		"practice1":    "https://www.formula1.com/en/results/2025/races/1270/singapore/practice/1",
		"practice2":    "https://www.formula1.com/en/results/2025/races/1270/singapore/practice/2",
		"practice3":    "https://www.formula1.com/en/results/2025/races/1270/singapore/practice/3",
		"pit_stops":    "https://www.formula1.com/en/results/2025/races/1270/singapore/pit-stop-summary",
		"fastest_laps": "https://www.formula1.com/en/results/2025/races/1270/singapore/fastest-laps",
		"gp_index":     "18",
	},
	"spanish": {
		"name":         "Spanish Grand Prix",
		"race":         "https://www.formula1.com/en/results/2025/races/1262/spain/race-result",
		"qualifying":   "https://www.formula1.com/en/results/2025/races/1262/spain/qualifying",
		"practice1":    "https://www.formula1.com/en/results/2025/races/1262/spain/practice/1",
		"practice2":    "https://www.formula1.com/en/results/2025/races/1262/spain/practice/2",
		"practice3":    "https://www.formula1.com/en/results/2025/races/1262/spain/practice/3",
		"pit_stops":    "https://www.formula1.com/en/results/2025/races/1262/spain/pit-stop-summary",
		"fastest_laps": "https://www.formula1.com/en/results/2025/races/1262/spain/fastest-laps",
		"gp_index":     "9",
	},
	"united_states": {
		"name":         "United States Grand Prix",
		"race":         "https://www.formula1.com/en/results/2025/races/1273/united-states/race-result",
		"qualifying":   "https://www.formula1.com/en/results/2025/races/1273/united-states/qualifying",
		"practice1":    "https://www.formula1.com/en/results/2025/races/1273/united-states/practice/1",
		"practice2":    "https://www.formula1.com/en/results/2025/races/1273/united-states/practice/2",
		"practice3":    "https://www.formula1.com/en/results/2025/races/1273/united-states/practice/3",
		"pit_stops":    "https://www.formula1.com/en/results/2025/races/1273/united-states/pit-stop-summary",
		"fastest_laps": "https://www.formula1.com/en/results/2025/races/1273/united-states/fastest-laps",
		"gp_index":     "19",
	},
	"abu_dhabi": {
		"name":         "Abu Dhabi Grand Prix",
		"race":         "https://www.formula1.com/en/results/2025/races/1277/abu-dhabi/race-result",
		"qualifying":   "https://www.formula1.com/en/results/2025/races/1277/abu-dhabi/qualifying",
		"practice1":    "https://www.formula1.com/en/results/2025/races/1277/abu-dhabi/practice/1",
		"practice2":    "https://www.formula1.com/en/results/2025/races/1277/abu-dhabi/practice/2",
		"practice3":    "https://www.formula1.com/en/results/2025/races/1277/abu-dhabi/practice/3",
		"pit_stops":    "https://www.formula1.com/en/results/2025/races/1277/abu-dhabi/pit-stop-summary",
		"fastest_laps": "https://www.formula1.com/en/results/2025/races/1277/abu-dhabi/fastest-laps",
		"gp_index":     "24",
	},
}

// GetGPURLs devuelve las URLs de un GP específico
func GetGPURLs(gpKey string) (map[string]string, bool) {
	urls, exists := GPURLs[gpKey]
	return urls, exists
}

// GetAllGPKeys devuelve todas las claves de GP disponibles
func GetAllGPKeys() []string {
	keys := make([]string, 0, len(GPURLs))
	for k := range GPURLs {
		keys = append(keys, k)
	}
	return keys
}
